spring.application.name=notification-service

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# Custom retry TTL (optional, defaults to 60000ms)
rabbitmq.retry.ttl-ms=300000

# Firebase Configuration
app.firebase.config-path=classpath:firebase-service-account.json
# Set mock-mode to false to use actual Firebase Admin SDK with the key file
app.firebase.mock-mode=false