name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5


      - name: Start services
        run: docker compose up 


      - name: Check containers
        run: docker ps


      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Run tests
        run: mvn clean test


      - name: Build
        run: mvn clean package -DskipTests
